default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: bass_lab_development
  cable:
    <<: *default
    database: bass_lab_cable_development
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: bass_lab_test

production:
  primary:
    <<: *default
    database: bass_lab_production
    username: bass_lab
    password: <%= ENV["BASS_LAB_DATABASE_PASSWORD"] %>
  cable:
    <<: *default
    database: bass_lab_cable_production
    migrations_paths: db/cable_migrate
    username: bass_lab
    password: <%= ENV["BASS_LAB_DATABASE_PASSWORD"] %>
